apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service-rest-deployment
  labels:
    app: event-service-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service-rest
  template:
    metadata:
      labels:
        app: event-service-rest
    spec:
      containers:
        - name: event-service-rest
          image: registry.gitlab.com/hasseltse-wafel/event-service/rest:latest
          ports:
            - containerPort: 80