apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-rest-deployment
  labels:
    app: user-service-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-rest
  template:
    metadata:
      labels:
        app: user-service-rest
    spec:
      containers:
        - name: user-service-rest
          image: registry.gitlab.com/hasseltse-wafel/user-service/rest:latest
          ports:
            - containerPort: 80