apiVersion: v1
kind: Service
metadata:
  name: event-service-rest-service
spec:
  type: ClusterIP
  selector:
    app: event-service-rest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001